#include<stdio.h>
main()
{
int a,b,c,d,e,f,i,j,x,y,m,n,q,k,t,count;
int *res;
char *sub,*str;
clrscr();
scanf("%d",&t);
for(i=0;i<t;i++)
{
	scanf("%d",&n);
	str=(char*)calloc(n,sizeof(char));
	scanf("%s",str);
	scanf("%d",&q);
	res=(int*)calloc(q,sizeof(int));
	for(j=0,x=0;j<q;j++,x++)
	{
		scanf("%d",&m);
		scanf("%d",&k);
		sub=(char*)calloc(k,sizeof(char));
		for(b=m,a=0;b<m+k;b++,a++)
		{
			sub[a]=str[b];
		}
		count=0;
		for(c=0;str[c]!='\0';c++)
		{
			if(sub[0]==str[c])
			{
				d=1;
				for(e=c+1,f=1;e<c+k;e++,f++)
				{
					if(sub[f]==str[e])
					d++;
					else
					break;
				}
				if(d==k)
				count++;
			}
		}
		res[x]=count;
	}
	for(y=0;y<q;y++)
	printf("\n%d",res[y]);
}
}

