main()
{
      int t,m[10000][2],i,j,k,a[10000][10000]={-1},max;
      scanf("%d",&t);
      for(i=0;i<t;i++)
      {
                      scanf("%d %d",&m[i][0],&m[i][1]);
                      }
      max=m[0][0];
      /*
      for(i=0;i<t;i++)
      {
                      if(max<m[i][0])
                      {
                                     max=m[i][0];
                                     }
                                     }
      for(i=0;i<t;i++)
      {
                      if(max<m[i][1])
                      {
                                    max=m[i][1];
                                    }
                                    }
      for(i=0;i<max;i++)
      {
                        a[0][i]=i;
                        a[i][0]=i;
                        a[i][i]=0;
                        }
      for(i=0;i<max;i++)
      {
                        for(j=0;j<max;j++)
                        {
                                          printf("%d",m[i][j]);
                                          }
                        printf("\n");
                        }
      */
      getch();
      }
