#include<stdio.h>
main()
{
      int t,m[10000][2],i,j,k,l,a[10000][10000]={0},max,min,boob;
      scanf("%d",&t);
      for(i=0;i<t;i++)
      {
                      scanf("%d %d",&m[i][0],&m[i][1]);
                      }
      max=m[0][0];
      for(i=0;i<t;i++)
      {
                      if(max<m[i][0])
                      {
                                     max=m[i][0];
                                     }
                                     }
      for(i=0;i<t;i++)
      {
                      if(max<m[i][1])
                      {
                                    max=m[i][1];
                                    }
                                    }
      max++;
      for(i=0;i<max;i++)
      {
                        for(j=0;j<max;j++)
                        {
                                          a[i][j]=-1;
                                          }
                                          }
      for(i=0;i<max;i++)
      {
                        a[0][i]=i;
                        a[i][0]=i;
                        a[i][i]=0;
                        }
      //Here begins the filling of numbers
      for(i=1;i<max;i++)
      {
                        for(j=1;j<max;j++)
                        {
                                       if(a[i][j]<=0)
                                       {
                                                     min=0;
                                                     boob=i;
                                                     if(j>i)
                                                     {
                                                            boob=j;
                                                            }
                                                     for(l=0;l<=boob;l++)
                                                     {
                                                     for(k=0;k<i;k++)
                                                     {
                                                                     if(a[k][j]==min)
                                                                     {
                                                                                    min++;
                                                                                    }
                                                                     }
                                                     for(k=0;k<j;k++)
                                                     {
                                                                     if(a[i][k]==min)
                                                                     {
                                                                                    min++;
                                                                                    }
                                                                     }
                                                                     }
                                                     a[i][j]=min;
                                                     
                                                     }
                                       }
                        }
                        /*
      for(i=0;i<max;i++)
      {
                        for(j=0;j<max;j++)
                        {
                        printf("%d ",a[i][j]);
                        }
                        printf("\n");
                        }
                        */
      for(i=0;i<t;i++)
      {
                      printf("%d",a[(m[i][0])][(m[i][1])]);
                      if(i!=t-1)
                      {
                                 printf("\n");
                                 }
                                 }                                                                        
      return 0;
      }
